:bug: PIC-757: Suppressed length when not available
ministryofjustice/prepare-a-case pull request #169
Opened 2020-09-23 13:35 UTC by katie-cawthorne

2020-09-23 15:48 UTC, theDustRoom approved these changes
👍

2020-09-23 15:49 UTC, theDustRoom commented
Oops, filing test.

2020-09-23 15:49 UTC, theDustRoom requested changes
Sorry, there's a failing test

2020-09-24 07:18 UTC, katie-cawthorne commented on mappings/community/DX12340A-convictions.json
> -            "description": "Fine",
All tests are passing locally but in CI the integration tests are timing out before they complete (tests are passing before it times out) with error `Too long with no output (exceeded 10m0s): context deadline exceeded` 🙄
I've changed the mock data that I amended, not that I can see any reason that this should cause the tests to timeout but just want to see if it passes.
I can't see what's causing the timeout issue.

2020-09-24 08:24 UTC, theDustRoom approved these changes
LGTM

2020-09-24 08:24 UTC, merged