PIC-1380: Dynamically display PSR in brackets next to probation status in the key details banner
ministryofjustice/prepare-a-case pull request #417
Opened 2021-05-27 14:53 UTC by sarahyjja

2021-05-27 16:10 UTC, theDustRoom commented on integration-tests/integration/features/case-summary.feature
> +    And I should see the body text "Probation status: Possible ndelius record"
We still need to display this as "NDelius"

2021-05-27 16:10 UTC, theDustRoom commented on server/views/components/key-details-bar/template.njk
> +                             {{ params.probationStatus | string | capitalize + ' (PSR)' }}
I believe that this is dependent on the new `awaitingPsr` flag in the data, not to be displayed all the time.

2021-05-27 16:11 UTC, theDustRoom requested changes
Comments inline

2021-06-07 10:51 UTC, katie-cawthorne approved these changes

2021-06-07 12:35 UTC, theDustRoom approved these changes

2021-06-07 12:35 UTC, merged