Pic 2606 - user server side paging
ministryofjustice/prepare-a-case pull request #708
Opened 2022-12-05 17:46 UTC by rschallapalli

2022-12-06 10:22 UTC, vb-moj commented
Blocked this until we discuss this corresponding to the back-end change @rschallapalli

2022-12-06 10:22 UTC, vb-moj requested changes
Please see my comment.

2022-12-06 13:31 UTC, vb-moj submitted a review, later dismissed

2022-12-15 09:04 UTC, vb-moj approved these changes

2023-09-11 08:39 UTC, closed without merging

2023-09-11 08:40 UTC, rschallapalli commented
implemented in a different PR