PIC-3759: Stop filters persisting
ministryofjustice/prepare-a-case pull request #919
Opened 2024-04-03 14:59 UTC by ArronChave3

2024-04-04 09:06 UTC, johnyfarrar commented on tests/routes/view.test.js
> +          console.log(response)
Console Log

2024-04-08 09:48 UTC, andrewcharnley commented on server/views/case-list.njk
> +    hello
Hello Arron!

2024-04-08 09:50 UTC, andrewcharnley requested changes
L314

2024-04-08 10:04 UTC, ArronChave3 commented on server/views/case-list.njk
> +    hello
hi

2024-04-08 17:21 UTC, andrewcharnley approved these changes

2024-04-08 17:21 UTC, merged