Feature/pic 3566 persist filters
ministryofjustice/prepare-a-case pull request #974
Opened 2024-08-02 09:57 UTC by ArronChave3

2024-08-13 09:22 UTC, johnyfarrar requested changes
One quick change but the tests are failing too...

2024-08-13 09:22 UTC, johnyfarrar commented on server/services/case-service.js
> +      console.log('🚀 ~ createCaseService ~ response:', response)
Might need to remove this....

2024-08-19 10:25 UTC, sameermoj submitted a review, later dismissed

2024-08-19 13:31 UTC, johnyfarrar requested changes
Just removing a couple of console logs

2024-08-19 13:31 UTC, johnyfarrar commented on public/src/javascripts/filter-component.js
> +      console.log(Object.fromEntries(formData));
Just got this one to remove

2024-08-19 13:31 UTC, johnyfarrar commented on public/src/javascripts/filter-component.js
> +      console.log('Reset filters button clicked')
Another one...

2024-08-20 08:29 UTC, johnyfarrar approved these changes
Great work

2024-08-20 08:30 UTC, merged